name: dart_zaim_client
description: A client package that use Zaim API.
version: 0.0.1
author: naoki85
homepage: https://github.com/naoki85/dart_zaim_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  oauth1: ^1.0.1

dev_dependencies:
  test: ^1.14.5
