name: dart_zaim_client
description: |
  A Project that was made to make using the Zaim API from flutter and dart.
  this package is depended on oauth1.
version: 0.0.2
homepage: https://github.com/naoki85/dart_zaim_client

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  oauth1: ^1.0.1

dev_dependencies:
  test: ^1.14.5
